// flow-typed signature: 112a0fee64e641066e7f718ee98b413a
// flow-typed version: <<STUB>>/cardinal_v1.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cardinal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cardinal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cardinal/bin/cdl' {
  declare module.exports: any;
}

declare module 'cardinal/cardinal' {
  declare module.exports: any;
}

declare module 'cardinal/examples/highlight-json' {
  declare module.exports: any;
}

declare module 'cardinal/examples/highlight-self-hide-semicolons' {
  declare module.exports: any;
}

declare module 'cardinal/examples/highlight-self' {
  declare module.exports: any;
}

declare module 'cardinal/examples/highlight-string' {
  declare module.exports: any;
}

declare module 'cardinal/lib/highlight' {
  declare module.exports: any;
}

declare module 'cardinal/lib/highlightFile' {
  declare module.exports: any;
}

declare module 'cardinal/lib/highlightFileSync' {
  declare module.exports: any;
}

declare module 'cardinal/settings' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-block-comment' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-diff-spike' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-file-async' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-file-sync' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-git-diff' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-json-file-async' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-json-file-sync' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-json' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-highlight-string' {
  declare module.exports: any;
}

declare module 'cardinal/test/cardinal-smoke' {
  declare module.exports: any;
}

declare module 'cardinal/test/fixtures/block-comment' {
  declare module.exports: any;
}

declare module 'cardinal/test/fixtures/custom' {
  declare module.exports: any;
}

declare module 'cardinal/test/fixtures/foo-with-errors' {
  declare module.exports: any;
}

declare module 'cardinal/test/fixtures/foo' {
  declare module.exports: any;
}

declare module 'cardinal/test/settings' {
  declare module.exports: any;
}

declare module 'cardinal/test/themes' {
  declare module.exports: any;
}

declare module 'cardinal/themes/default' {
  declare module.exports: any;
}

declare module 'cardinal/themes/empty' {
  declare module.exports: any;
}

declare module 'cardinal/themes/hide-semicolons' {
  declare module.exports: any;
}

declare module 'cardinal/themes/jq' {
  declare module.exports: any;
}

declare module 'cardinal/themes/tomorrow-night' {
  declare module.exports: any;
}

declare module 'cardinal/utl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cardinal/bin/cdl.js' {
  declare module.exports: $Exports<'cardinal/bin/cdl'>;
}
declare module 'cardinal/cardinal.js' {
  declare module.exports: $Exports<'cardinal/cardinal'>;
}
declare module 'cardinal/examples/highlight-json.js' {
  declare module.exports: $Exports<'cardinal/examples/highlight-json'>;
}
declare module 'cardinal/examples/highlight-self-hide-semicolons.js' {
  declare module.exports: $Exports<'cardinal/examples/highlight-self-hide-semicolons'>;
}
declare module 'cardinal/examples/highlight-self.js' {
  declare module.exports: $Exports<'cardinal/examples/highlight-self'>;
}
declare module 'cardinal/examples/highlight-string.js' {
  declare module.exports: $Exports<'cardinal/examples/highlight-string'>;
}
declare module 'cardinal/lib/highlight.js' {
  declare module.exports: $Exports<'cardinal/lib/highlight'>;
}
declare module 'cardinal/lib/highlightFile.js' {
  declare module.exports: $Exports<'cardinal/lib/highlightFile'>;
}
declare module 'cardinal/lib/highlightFileSync.js' {
  declare module.exports: $Exports<'cardinal/lib/highlightFileSync'>;
}
declare module 'cardinal/settings.js' {
  declare module.exports: $Exports<'cardinal/settings'>;
}
declare module 'cardinal/test/cardinal-highlight-block-comment.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-block-comment'>;
}
declare module 'cardinal/test/cardinal-highlight-diff-spike.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-diff-spike'>;
}
declare module 'cardinal/test/cardinal-highlight-file-async.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-file-async'>;
}
declare module 'cardinal/test/cardinal-highlight-file-sync.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-file-sync'>;
}
declare module 'cardinal/test/cardinal-highlight-git-diff.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-git-diff'>;
}
declare module 'cardinal/test/cardinal-highlight-json-file-async.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-json-file-async'>;
}
declare module 'cardinal/test/cardinal-highlight-json-file-sync.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-json-file-sync'>;
}
declare module 'cardinal/test/cardinal-highlight-json.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-json'>;
}
declare module 'cardinal/test/cardinal-highlight-string.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-highlight-string'>;
}
declare module 'cardinal/test/cardinal-smoke.js' {
  declare module.exports: $Exports<'cardinal/test/cardinal-smoke'>;
}
declare module 'cardinal/test/fixtures/block-comment.js' {
  declare module.exports: $Exports<'cardinal/test/fixtures/block-comment'>;
}
declare module 'cardinal/test/fixtures/custom.js' {
  declare module.exports: $Exports<'cardinal/test/fixtures/custom'>;
}
declare module 'cardinal/test/fixtures/foo-with-errors.js' {
  declare module.exports: $Exports<'cardinal/test/fixtures/foo-with-errors'>;
}
declare module 'cardinal/test/fixtures/foo.js' {
  declare module.exports: $Exports<'cardinal/test/fixtures/foo'>;
}
declare module 'cardinal/test/settings.js' {
  declare module.exports: $Exports<'cardinal/test/settings'>;
}
declare module 'cardinal/test/themes.js' {
  declare module.exports: $Exports<'cardinal/test/themes'>;
}
declare module 'cardinal/themes/default.js' {
  declare module.exports: $Exports<'cardinal/themes/default'>;
}
declare module 'cardinal/themes/empty.js' {
  declare module.exports: $Exports<'cardinal/themes/empty'>;
}
declare module 'cardinal/themes/hide-semicolons.js' {
  declare module.exports: $Exports<'cardinal/themes/hide-semicolons'>;
}
declare module 'cardinal/themes/jq.js' {
  declare module.exports: $Exports<'cardinal/themes/jq'>;
}
declare module 'cardinal/themes/tomorrow-night.js' {
  declare module.exports: $Exports<'cardinal/themes/tomorrow-night'>;
}
declare module 'cardinal/utl.js' {
  declare module.exports: $Exports<'cardinal/utl'>;
}
