// flow-typed signature: 63d4988c2419251bba9779be6bf6c6da
// flow-typed version: <<STUB>>/cli-ux_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-ux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-ux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-ux/lib/action/base' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/action/simple' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/action/spinner' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/action/spinners' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/base' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/config' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/deps' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/errors' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/exit_error' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/index' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/prompt' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/screen' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/stream' {
  declare module.exports: any;
}

declare module 'cli-ux/lib/table' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-ux/lib/action/base.js' {
  declare module.exports: $Exports<'cli-ux/lib/action/base'>;
}
declare module 'cli-ux/lib/action/simple.js' {
  declare module.exports: $Exports<'cli-ux/lib/action/simple'>;
}
declare module 'cli-ux/lib/action/spinner.js' {
  declare module.exports: $Exports<'cli-ux/lib/action/spinner'>;
}
declare module 'cli-ux/lib/action/spinners.js' {
  declare module.exports: $Exports<'cli-ux/lib/action/spinners'>;
}
declare module 'cli-ux/lib/base.js' {
  declare module.exports: $Exports<'cli-ux/lib/base'>;
}
declare module 'cli-ux/lib/config.js' {
  declare module.exports: $Exports<'cli-ux/lib/config'>;
}
declare module 'cli-ux/lib/deps.js' {
  declare module.exports: $Exports<'cli-ux/lib/deps'>;
}
declare module 'cli-ux/lib/errors.js' {
  declare module.exports: $Exports<'cli-ux/lib/errors'>;
}
declare module 'cli-ux/lib/exit_error.js' {
  declare module.exports: $Exports<'cli-ux/lib/exit_error'>;
}
declare module 'cli-ux/lib/index.js' {
  declare module.exports: $Exports<'cli-ux/lib/index'>;
}
declare module 'cli-ux/lib/prompt.js' {
  declare module.exports: $Exports<'cli-ux/lib/prompt'>;
}
declare module 'cli-ux/lib/screen.js' {
  declare module.exports: $Exports<'cli-ux/lib/screen'>;
}
declare module 'cli-ux/lib/stream.js' {
  declare module.exports: $Exports<'cli-ux/lib/stream'>;
}
declare module 'cli-ux/lib/table.js' {
  declare module.exports: $Exports<'cli-ux/lib/table'>;
}
