// flow-typed signature: 02728891102373a1de98d6924d2a4b50
// flow-typed version: <<STUB>>/heroku-client_v3.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-client/lib/request' {
  declare module.exports: any;
}

declare module 'heroku-client/lib/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-client/index' {
  declare module.exports: $Exports<'heroku-client'>;
}
declare module 'heroku-client/index.js' {
  declare module.exports: $Exports<'heroku-client'>;
}
declare module 'heroku-client/lib/request.js' {
  declare module.exports: $Exports<'heroku-client/lib/request'>;
}
declare module 'heroku-client/lib/url.js' {
  declare module.exports: $Exports<'heroku-client/lib/url'>;
}
