// flow-typed signature: 73f03cb75eedf471e30d1d5b0c77ad51
// flow-typed version: <<STUB>>/lodash.keys_v^4.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.keys/index' {
  declare module.exports: $Exports<'lodash.keys'>;
}
declare module 'lodash.keys/index.js' {
  declare module.exports: $Exports<'lodash.keys'>;
}
