// flow-typed signature: d2254140e5aa5ad3a2471c142cf8477e
// flow-typed version: <<STUB>>/lodash.identity_v^3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.identity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.identity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.identity/index' {
  declare module.exports: $Exports<'lodash.identity'>;
}
declare module 'lodash.identity/index.js' {
  declare module.exports: $Exports<'lodash.identity'>;
}
