// flow-typed signature: 14f46136706f5a70a58ef0bb0d4b81e7
// flow-typed version: <<STUB>>/pretty-format_v20.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-format/build-es5/index' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/AsymmetricMatcher' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ConvertAnsi' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/HTMLElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableList' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableMap' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableOrderedMap' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableOrderedSet' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutablePlugins' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableSet' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ImmutableStack' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/lib/escapeHTML' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/lib/printImmutable' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ReactElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build-es5/plugins/ReactTestComponent' {
  declare module.exports: any;
}

declare module 'pretty-format/build/index' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/AsymmetricMatcher' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ConvertAnsi' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/HTMLElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableList' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableMap' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableOrderedMap' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableOrderedSet' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutablePlugins' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableSet' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ImmutableStack' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/escapeHTML' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/printImmutable' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactTestComponent' {
  declare module.exports: any;
}

declare module 'pretty-format/perf/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-format/build-es5/index.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/index'>;
}
declare module 'pretty-format/build-es5/plugins/AsymmetricMatcher.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/AsymmetricMatcher'>;
}
declare module 'pretty-format/build-es5/plugins/ConvertAnsi.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ConvertAnsi'>;
}
declare module 'pretty-format/build-es5/plugins/HTMLElement.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/HTMLElement'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableList.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableList'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableMap.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableMap'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableOrderedMap.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableOrderedMap'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableOrderedSet.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableOrderedSet'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutablePlugins.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutablePlugins'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableSet.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableSet'>;
}
declare module 'pretty-format/build-es5/plugins/ImmutableStack.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ImmutableStack'>;
}
declare module 'pretty-format/build-es5/plugins/lib/escapeHTML.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/lib/escapeHTML'>;
}
declare module 'pretty-format/build-es5/plugins/lib/printImmutable.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/lib/printImmutable'>;
}
declare module 'pretty-format/build-es5/plugins/ReactElement.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ReactElement'>;
}
declare module 'pretty-format/build-es5/plugins/ReactTestComponent.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/plugins/ReactTestComponent'>;
}
declare module 'pretty-format/build/index.js' {
  declare module.exports: $Exports<'pretty-format/build/index'>;
}
declare module 'pretty-format/build/plugins/AsymmetricMatcher.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/AsymmetricMatcher'>;
}
declare module 'pretty-format/build/plugins/ConvertAnsi.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ConvertAnsi'>;
}
declare module 'pretty-format/build/plugins/HTMLElement.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/HTMLElement'>;
}
declare module 'pretty-format/build/plugins/ImmutableList.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableList'>;
}
declare module 'pretty-format/build/plugins/ImmutableMap.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableMap'>;
}
declare module 'pretty-format/build/plugins/ImmutableOrderedMap.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableOrderedMap'>;
}
declare module 'pretty-format/build/plugins/ImmutableOrderedSet.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableOrderedSet'>;
}
declare module 'pretty-format/build/plugins/ImmutablePlugins.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutablePlugins'>;
}
declare module 'pretty-format/build/plugins/ImmutableSet.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableSet'>;
}
declare module 'pretty-format/build/plugins/ImmutableStack.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ImmutableStack'>;
}
declare module 'pretty-format/build/plugins/lib/escapeHTML.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/escapeHTML'>;
}
declare module 'pretty-format/build/plugins/lib/printImmutable.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/printImmutable'>;
}
declare module 'pretty-format/build/plugins/ReactElement.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactElement'>;
}
declare module 'pretty-format/build/plugins/ReactTestComponent.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactTestComponent'>;
}
declare module 'pretty-format/perf/test.js' {
  declare module.exports: $Exports<'pretty-format/perf/test'>;
}
