// flow-typed signature: 34914553c685236a1b3567377bf320be
// flow-typed version: <<STUB>>/std-mocks_v1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'std-mocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'std-mocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'std-mocks/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'std-mocks/index' {
  declare module.exports: $Exports<'std-mocks'>;
}
declare module 'std-mocks/index.js' {
  declare module.exports: $Exports<'std-mocks'>;
}
declare module 'std-mocks/test.js' {
  declare module.exports: $Exports<'std-mocks/test'>;
}
