#!/usr/bin/env node

// an example of creating a cli-engine-command command that lists the files in a directory
// check out the typescript example as it is a bit cleaner and does the same thing

const {Command, flags} = require('..') // require('cli-engine-command') outisde of this repo
const fs = require('fs')

class LS extends Command {
  constructor () {
    super()
    this.Flags = {
      dir: flags.string({
        char: 'd',
        default: process.cwd()
      })
    }
  }

  async run () {
    let files = fs.readdirSync(this.flags.dir)
    for (let f of files) {
      this.out.log(f)
    }
  }
}
LS.run()
